
#
# Run all tests
#
make test:
  rules:
    - when: manual
    - changes:
      - "**/*.sh"
  image: "registry.bihealth.org:443/bockm/recipes/testenv:bash-container-library"
  before_script:
    - . /etc/profile || true
  script:
    - make --keep-going test

#
# Individual tests
#
include:
  - test.yml

#
# Synchronize GitHub repository
#
sync github:
  rules:
    - when: always
  image: "registry.bihealth.org:443/bockm/recipes/debian:bullseye-amd64"
  before_script:
    - . /etc/profile || true
    - git remote rm bih || true
    - git remote rm github || true
  script:
    - git remote add bih https://git.bihealth.org/bockm/bash-container-library.git
    - git remote add github https://github.com/matthiasbock/bash-container-library.git
    - git checkout ${CI_COMMIT_BRANCH}
    - git pull --ff-only bih ${CI_COMMIT_BRANCH}
    - git pull --ff-only github ${CI_COMMIT_BRANCH}
    - git push bih ${CI_COMMIT_BRANCH}
    - git push github ${CI_COMMIT_BRANCH}
  after_script:
    - git remote rm bih || true
    - git remote rm github || true
