
# Include guard
constants_sh="$(realpath "${BASH_SOURCE[0]}")"

#
# Function return codes
#
SUCCESS=0

ERROR_ILLEGAL_CONTAINER_CLI=10
ERROR_MISSING_ARGUMENT=11
ERROR_ILLEGAL_ARGUMENT=12
ERROR_ASSET_NOT_FOUND=13

ERROR_CONTAINER_EXISTS=22
ERROR_CONTAINER_NOT_FOUND=23
ERROR_CONTAINER_RUNNING=24
ERROR_CONTAINER_NOT_RUNNING=25

ERROR_IMAGE_AVAILABLE=30
ERROR_IMAGE_NOT_AVAILABLE=31

ERROR_COMMAND_FAILED=50
ERROR_CRAWLER_MISSING=51
ERROR_CRAWLER_FAILED=52
ERROR_PARSING_FAILED=53
ERROR_JQ_FAILED=54

#
# GitHub constants
#
ERROR_GITHUB_API=60
ERROR_GITHUB_JSON=61
